### ISSUE TITLE
Gulp error with Nodejs version

### ISSUE THREAD

**Issue by paolavrgs** [enmachs/front-env#29]
**What were you expecting to happen?**
Gulp runs normally

**What actually happened?**
Gulp throws the following error:

```bash
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
```

Node: v12.15.5
Gulp: v3.9.1

I downgrade Node to the v10.20.1, then Gulp throws another error:
```
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15

```

**Comment by enmachs** [comment]
Need to add support for node 12

**Comment by enmachs** [comment]
Did replicate error with node v12.15.0 (using  nvm)

**Comment by enmachs** [comment]
Issue solved
